// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/rpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b74175b916d80a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type Response struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Epoch                int64    `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_42b74175b916d80a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Response) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() {
	proto.RegisterFile("pkg/proto/rpc.proto", fileDescriptor_42b74175b916d80a)
}

var fileDescriptor_42b74175b916d80a = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xc8, 0x4e, 0xd7,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2a, 0x48, 0xd6, 0x03, 0xb3, 0x84, 0x58, 0xc1, 0x94,
	0x92, 0x02, 0x17, 0x7b, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x28, 0x17, 0x5b, 0x62,
	0x41, 0x41, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x6b, 0x62, 0x41, 0x81,
	0x67, 0x8a, 0x92, 0x3b, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x0e, 0x25,
	0x42, 0x22, 0x5c, 0xac, 0xa9, 0x05, 0xf9, 0xc9, 0x19, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x10, 0x8e, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0x33, 0x58, 0x88, 0x29, 0x33, 0xc5, 0xc8,
	0x9a, 0x8b, 0x2d, 0x28, 0x35, 0x31, 0x25, 0xb5, 0x48, 0xc8, 0x90, 0x8b, 0xc7, 0xb9, 0x28, 0x35,
	0xb1, 0x24, 0x35, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x57, 0x88, 0x0f, 0xe2, 0x26, 0x3d, 0xa8, 0x4b,
	0xa4, 0xf8, 0xe1, 0x7c, 0x88, 0xbd, 0x06, 0x8c, 0x49, 0x6c, 0x60, 0x11, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x20, 0xd4, 0x2c, 0xcc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReaderClient is the client API for Reader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReaderClient interface {
	CreateStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Reader_CreateStreamClient, error)
}

type readerClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderClient(cc grpc.ClientConnInterface) ReaderClient {
	return &readerClient{cc}
}

func (c *readerClient) CreateStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Reader_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Reader_serviceDesc.Streams[0], "/proto.Reader/CreateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &readerCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Reader_CreateStreamClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type readerCreateStreamClient struct {
	grpc.ClientStream
}

func (x *readerCreateStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReaderServer is the server API for Reader service.
type ReaderServer interface {
	CreateStream(*Request, Reader_CreateStreamServer) error
}

// UnimplementedReaderServer can be embedded to have forward compatible implementations.
type UnimplementedReaderServer struct {
}

func (*UnimplementedReaderServer) CreateStream(req *Request, srv Reader_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}

func RegisterReaderServer(s *grpc.Server, srv ReaderServer) {
	s.RegisterService(&_Reader_serviceDesc, srv)
}

func _Reader_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReaderServer).CreateStream(m, &readerCreateStreamServer{stream})
}

type Reader_CreateStreamServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type readerCreateStreamServer struct {
	grpc.ServerStream
}

func (x *readerCreateStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

var _Reader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Reader",
	HandlerType: (*ReaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStream",
			Handler:       _Reader_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/rpc.proto",
}
